### ISSUE TITLE
Cleanup branches

### ISSUE THREAD

**Issue by gavanderhoorn** [sam-xl/abb_experimental#1]
With https://github.com/ros-industrial/abb_experimental/pull/112 merged (via https://github.com/ros-industrial/abb_experimental/pull/117), it looks like we can cleanup some of the branches in this fork.

Suggestion:

 - remove `abb_irb4600_variants`
 - hard reset `kinetic-devel` to `upstream/kinetic-devel`

I can do this, but wanted to make sure we don't have any deployments or cells using these branches right now.

@dave992 @rtonnaer: could you check and/or confirm?

**Comment by dave992** [comment]
Agreed, the whole purpose of this repo was to have support for the IRB4600 variant we have here. 

I'll have a look at the repositories which need an update. Furthermore, the impact on running projects should be minimal. When I am at my PC I'll delete the `add_irb4600_variants` branch and reset `kinetic-devel`, feel free to do so if you are faster ;)

**Comment by gavanderhoorn** [comment]
> feel free to do so if you are faster ;)

Let's make sure only one of us does this.

I'll let you make the changes.

Don't forget to force-push to `kinetic-devel` here in this fork, so we are completely in-sync with upstream.

**Comment by dave992** [comment]
Deleted the `add_irb4600_variants` branch and performed a hard reset of `kinetic-devel` to `upstream/kinetic-devel`. Closing this issue.
